import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:water_habit_app/core/localization/localization_providers.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'auth.loginTitle': 'Đăng nhập 💧',
      'auth.loginSubtitle': 'Tiếp tục hành trình uống nước của bạn',
      'auth.emailLabel': 'Email',
      'auth.emailHint': 'Nhập email của bạn',
      'auth.passwordLabel': 'Mật khẩu',
      'auth.passwordHint': 'Nhập mật khẩu',
      'auth.confirmPasswordLabel': 'Xác nhận mật khẩu',
      'auth.confirmPasswordHint': 'Nhập lại mật khẩu',
      'auth.loginButton': 'Đăng nhập',
      'auth.registerButton': 'Đăng ký',
      'auth.dontHaveAccount': 'Chưa có tài khoản? Đăng ký ngay',
      'auth.alreadyHaveAccount': 'Đã có tài khoản? Đăng nhập',
      'auth.forgotPassword': 'Quên mật khẩu?',
      'auth.or': 'hoặc',
      'auth.registerTitle': 'Tạo tài khoản mới 🌱',
      'auth.registerSubtitle': 'Bắt đầu hành trình sức khỏe',
      'auth.usernameLabel': 'Tên người dùng (Username)',
      'auth.agreeTerms': 'Tôi đồng ý với Điều khoản và Chính sách bảo mật',
      'auth.agreeTermsRequired': 'Vui lòng đồng ý điều khoản sử dụng',
      'splash.tagline': 'Uống nước. Kết nối. Phát triển. 🌱',
      
      'home.title': 'Chào ngày mới! ☀️',
      'home.hey': 'Bạn ơi! 🌿',
      'home.progressCircleMetric': 'đã uống',
      'home.targetLabel': 'Mục tiêu',
      'home.characterLevel': 'Mầm Lv.',
      'home.supportMsg': 'Hãy tiếp tục nhé! 🌿',
      'home.quickAddTitle': 'Uống nhanh',
      'home.dailyLog': 'Nhật ký hôm nay',
      'home.dailyLogEmpty': 'Hôm nay chưa uống nước. Bắt đầu ngay nhé! 💧',
      
      'feed.title': 'Hoạt động 🌿',
      'feed.emptyFeed': 'Chưa có hoạt động',
      'feed.emptyFeedSubtitle': 'Thêm bạn bè để xem hoạt động! 🌱',
      'feed.findFriends': 'Tìm bạn',
      'feed.event0': 'đã hoàn thành mục tiêu hôm nay! 🎯',
      'feed.event1': 'đã mở khóa nơ mới! 🎀',
      'feed.event2': 'đã đạt chuỗi 30 ngày! 🔥',
      'feed.event3': 'đã gửi Water Boost cho bạn! 💧',
      'feed.event4': 'đã lên Level 15! ⬆️',
      
      'friends.title': 'Bạn bè 👥',
      'friends.searchPlaceholder': 'Tìm kiếm bằng username...',
      'friends.qrScan': 'Quét mã QR',
      'friends.qrShow': 'Mã QR của tôi',
      'friends.tabFriends': 'Danh sách',
      'friends.tabRequests': 'Lời mời',
      'friends.noFriends': 'Chưa có bạn bè',
      'friends.noFriendsSubtitle': 'Hãy kết nối để cùng nhau xây dựng thói quen tốt! 🌿',
      'friends.noRequestsTitle': 'Không có lời mời',
      'friends.noRequestsSubtitle': 'Các lời mời kết bạn sẽ xuất hiện ở đây',
      'friends.searchTitle': 'Tìm bạn bè 🔍',
      'friends.notFound': 'Không tìm thấy',
      'friends.sent': 'Đã gửi',
      'friends.addFriend': 'Kết bạn',
      
      'profile.title': 'Hồ sơ 👤',
      'profile.editProfile': 'Chỉnh sửa hồ sơ',
      'profile.addFriend': 'Kết bạn',
      'profile.sendSupport': 'Cổ vũ',
      'profile.tabStats': 'Chỉ số & Đồ thị',
      'profile.tabAchievements': 'Huy hiệu đạt được',
      'profile.chartTitle': '7 ngày gần đây',
      'profile.chartAvg': 'Trung bình',
      'profile.totalWater': 'Tổng nước',
      'profile.streakCount': 'Chuỗi ngày',
      'profile.friendCount': 'Bạn bè',
      'profile.achievementCount': 'Huy hiệu',
      'profile.statsDetailed': 'Thống kê chi tiết 🌿',
      'profile.daysTracked': 'Số ngày theo dõi',
      'profile.goalsCompleted': 'Mục tiêu hoàn thành',
      'profile.avgDaily': 'Trung bình uống',
      'profile.longestStreak': 'Chuỗi tốt nhất',
      'profile.languageLabel': 'Ngôn ngữ / Language',
      'profile.errorUserLoad': 'Không thể tải thông tin người dùng',
      'profile.notLoggedIn': 'Chưa đăng nhập',
      'profile.pleaseLogin': 'Vui lòng đăng nhập để xem hồ sơ',
      'profile.userDeleted': 'Người dùng không tồn tại hoặc đã bị xóa.',
      'profile.errorStats': 'Lỗi tải chỉ số',
      'profile.friendRequestSent': 'Đang gửi yêu cầu kết bạn...',
      'profile.cheered': 'Đã gửi lời cổ vũ nước! 💧',
      'profile.errorChart': 'Lỗi tải đồ thị tuần',
      'profile.daysSuffix': 'ngày',
      'profile.timesSuffix': 'lần',
      'profile.errorAchievements': 'Lỗi tải huy hiệu',
      'profile.noAchievements': 'Chưa có huy hiệu',
      'profile.noAchievementsSubtitle': 'Uống nước đều đặn để nhận các huy hiệu danh giá nhé! 🏆',
      'profile.bioLabel': 'Giới thiệu bản thân (Bio)',
      'profile.goalLabel': 'Mục tiêu nước hàng ngày (ml)',
      'profile.saveChanges': 'Lưu thay đổi',
      'profile.avatarLabel': 'Ảnh đại diện',
      'profile.presetAvatars': 'Chọn từ ảnh có sẵn:',
      'profile.displayNameLabel': 'Tên hiển thị',
      'profile.displayNameHint': 'Nhập tên của bạn',
      'profile.displayNameRequired': 'Vui lòng nhập tên hiển thị',
      'profile.goalRequired': 'Vui lòng nhập mục tiêu',
      'profile.goalPositive': 'Mục tiêu phải là số lớn hơn 0',
      'profile.goalRange': 'Mục tiêu khuyến nghị từ 1000ml đến 5000ml',
      'profile.saveSuccess': 'Hồ sơ đã được cập nhật thành công! 🎉',
      'profile.saveError': 'Đã xảy ra lỗi',
      
      'common.greetingLateNight': 'Chào buổi khuya',
      'common.greetingMorning': 'Chào buổi sáng',
      'common.greetingAfternoon': 'Chào buổi chiều',
      'common.greetingEvening': 'Chào buổi tối',
      'common.timeAgoJustNow': 'Vừa xong',
      'common.timeAgoMinutes': '{value} phút trước',
      'common.timeAgoHours': '{value} giờ trước',
      'common.timeAgoDays': '{value} ngày trước',
      'common.timeAgoWeeks': '{value} tuần trước',
      'common.timeAgoMonths': '{value} tháng trước',
      'common.timeAgoYears': '{value} năm trước',
    },
    'en': {
      'auth.loginTitle': 'Login 💧',
      'auth.loginSubtitle': 'Continue your hydration journey',
      'auth.emailLabel': 'Email',
      'auth.emailHint': 'Enter your email',
      'auth.passwordLabel': 'Password',
      'auth.passwordHint': 'Enter your password',
      'auth.confirmPasswordLabel': 'Confirm Password',
      'auth.confirmPasswordHint': 'Re-enter your password',
      'auth.loginButton': 'Login',
      'auth.registerButton': 'Register',
      'auth.dontHaveAccount': "Don't have an account? Register now",
      'auth.alreadyHaveAccount': 'Already have an account? Login',
      'auth.forgotPassword': 'Forgot password?',
      'auth.or': 'or',
      'auth.registerTitle': 'Create new account 🌱',
      'auth.registerSubtitle': 'Start your health journey',
      'auth.usernameLabel': 'Username',
      'auth.agreeTerms': 'I agree to the Terms of Use and Privacy Policy',
      'auth.agreeTermsRequired': 'Please agree to the terms of use',
      'splash.tagline': 'Hydrate. Connect. Grow. 🌱',
      
      'home.title': 'Good Morning! ☀️',
      'home.hey': 'Hey there! 🌿',
      'home.progressCircleMetric': 'drank',
      'home.targetLabel': 'Goal',
      'home.characterLevel': 'Sprout Lv.',
      'home.supportMsg': 'Keep it up! 🌿',
      'home.quickAddTitle': 'Quick Add',
      'home.dailyLog': "Today's Log",
      'home.dailyLogEmpty': 'No water logged today. Start now! 💧',
      
      'feed.title': 'Activity 🌿',
      'feed.emptyFeed': 'No activities',
      'feed.emptyFeedSubtitle': 'Add friends to see activity! 🌱',
      'feed.findFriends': 'Find Friends',
      'feed.event0': "completed today's goal! 🎯",
      'feed.event1': 'unlocked a new ribbon! 🎀',
      'feed.event2': 'reached a 30-day streak! 🔥',
      'feed.event3': 'sent you a Water Boost! 💧',
      'feed.event4': 'reached Level 15! ⬆️',
      
      'friends.title': 'Friends 👥',
      'friends.searchPlaceholder': 'Search by username...',
      'friends.qrScan': 'Scan QR Code',
      'friends.qrShow': 'My QR Code',
      'friends.tabFriends': 'List',
      'friends.tabRequests': 'Requests',
      'friends.noFriends': 'No friends yet',
      'friends.noFriendsSubtitle': 'Connect to build healthy habits together! 🌿',
      'friends.noRequestsTitle': 'No requests',
      'friends.noRequestsSubtitle': 'Friend requests will appear here',
      'friends.searchTitle': 'Find Friends 🔍',
      'friends.notFound': 'Not found',
      'friends.sent': 'Sent',
      'friends.addFriend': 'Add Friend',
      
      'profile.title': 'Profile 👤',
      'profile.editProfile': 'Edit Profile',
      'profile.addFriend': 'Add Friend',
      'profile.sendSupport': 'Cheer',
      'profile.tabStats': 'Stats & Charts',
      'profile.tabAchievements': 'Achievements',
      'profile.chartTitle': 'Last 7 Days',
      'profile.chartAvg': 'Average',
      'profile.totalWater': 'Total Water',
      'profile.streakCount': 'Streak',
      'profile.friendCount': 'Friends',
      'profile.achievementCount': 'Badges',
      'profile.statsDetailed': 'Detailed Stats 🌿',
      'profile.daysTracked': 'Days Tracked',
      'profile.goalsCompleted': 'Goals Completed',
      'profile.avgDaily': 'Daily Average',
      'profile.longestStreak': 'Longest Streak',
      'profile.languageLabel': 'Language / Ngôn ngữ',
      'profile.errorUserLoad': 'Could not load user info',
      'profile.notLoggedIn': 'Not logged in',
      'profile.pleaseLogin': 'Please log in to view profile',
      'profile.userDeleted': 'User does not exist or has been deleted.',
      'profile.errorStats': 'Error loading stats',
      'profile.friendRequestSent': 'Sending friend request...',
      'profile.cheered': 'Cheered! 💧',
      'profile.errorChart': 'Error loading weekly chart',
      'profile.daysSuffix': 'days',
      'profile.timesSuffix': 'times',
      'profile.errorAchievements': 'Error loading achievements',
      'profile.noAchievements': 'No achievements yet',
      'profile.noAchievementsSubtitle': 'Drink water regularly to receive prestigious badges! 🏆',
      'profile.bioLabel': 'Bio',
      'profile.goalLabel': 'Daily Water Goal (ml)',
      'profile.saveChanges': 'Save Changes',
      'profile.avatarLabel': 'Avatar',
      'profile.presetAvatars': 'Select from presets:',
      'profile.displayNameLabel': 'Display Name',
      'profile.displayNameHint': 'Enter your name',
      'profile.displayNameRequired': 'Please enter display name',
      'profile.goalRequired': 'Please enter goal',
      'profile.goalPositive': 'Goal must be greater than 0',
      'profile.goalRange': 'Recommended goal: 1000ml to 5000ml',
      'profile.saveSuccess': 'Profile updated successfully! 🎉',
      'profile.saveError': 'An error occurred',
      
      'common.greetingLateNight': 'Good night',
      'common.greetingMorning': 'Good morning',
      'common.greetingAfternoon': 'Good afternoon',
      'common.greetingEvening': 'Good evening',
      'common.timeAgoJustNow': 'Just now',
      'common.timeAgoMinutes': '{value}m ago',
      'common.timeAgoHours': '{value}h ago',
      'common.timeAgoDays': '{value}d ago',
      'common.timeAgoWeeks': '{value}w ago',
      'common.timeAgoMonths': '{value}mo ago',
      'common.timeAgoYears': '{value}y ago',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

extension BuildContextLocX on BuildContext {
  String tr(String key) {
    // Read the current locale from Riverpod
    final container = ProviderScope.containerOf(this, listen: false);
    final currentLocale = container.read(localeProvider);
    return AppLocalizations(currentLocale).translate(key);
  }
}
